PersonalMoneyManagerMVC.Web/Controllers/CategoryController.cs
using PersonalMoneyManagerMVC.Data.Interface;
using PersonalMoneyManagerMVC.Entity.DTO.Category;
using PersonalMoneyManagerMVC.Entity.Enum;
using PersonalMoneyManagerMVC.Entity.Model;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PersonalMoneyManagerMVC.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IRepository<Category> _categoryRepository;
        private ILogger _logger;
        

        public CategoryController(IRepository<Category> categoryRepo,ILogger logger)
        {
            _categoryRepository = categoryRepo;
            _logger = logger;
        }
        // GET: Category
      
        [HttpGet]
        public async Task<ActionResult> Create()
        {

            var createCategoryDto = new CreateCategoryDTO();
            return View(createCategoryDto);
        }

        [HttpPost]

        public async Task<ActionResult> Create(CreateCategoryDTO categoryDTO)
        {
            Category categoryEntity = new Category
            {
                Name = categoryDTO.Name,
                Icon = categoryDTO.SelectedIcon,
                IconColor = categoryDTO.SelectedColor,
                WithdrawOrProfit = categoryDTO.WithdrawOrProfit

            };

         
            _categoryRepository.Add(categoryEntity);
            
            await _categoryRepository.Save();
            await _logger.Log(LogType.Info, "Category add", categoryEntity,categoryEntity.Name,"");
            // todo: redirect to category page, not wallets
            return RedirectToAction("ShowAllWallets", "Wallet");
        }
    }
}

PersonalMoneyManagerMVC.Web/Controllers/LogController.cs
using PersonalMoneyManagerMVC.Data.Interface;
using PersonalMoneyManagerMVC.Entity.Model;
using PersonalMoneyManagerMVC.Entity.ViewModel.Logs;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PersonalMoneyManagerMVC.Web.Controllers
{
    public class LogController : Controller
    {
        private IRepository<Log> _logRepository;

        public LogController(IRepository<Log> logRepository)
        {
            _logRepository = logRepository;
        }
        public async Task<ActionResult> ShowLog(int page)
        {
            var itemsOnPage = 10;

            var logListViewModel = new LogListViewModel
            {
                logs = _logRepository.Get()
                    .OrderByDescending(x => x.Created)
                    .Skip((page - 1) * itemsOnPage)
                    .Select(x => new LogViewModel
                        {
                            Message = x.Message,
                            Type = x.Type.ToString(),
                            OldName = x.OldName,
                            NewName = x.NewName,
                            Created = x.Created.ToString()
                        }
                    ).Take(itemsOnPage)
                    .ToList(),

                PageInfo = new PageInfo
                {
                    Page = page,
                    PageCount = (int)Math.Ceiling((double)_logRepository.Get().Count() / itemsOnPage)
                }
            };


            return View(logListViewModel);

        }
    }
}

PersonalMoneyManagerMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid">

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
            <div class="list-group">

                <a href="@Url.Action("Dashboard","Home")" class="list-group-item active nameLabel">
                    Personal money manager
                </a>
             
                <div class="leftMenu col-lg-3 col-md-3 col-sm-12 col-xs-12 " >

                       
                    <a href='@Url.Action("Dashboard", "Home")' class="list-group-item">Dashboard<i class="glyphicon glyphicon-plus-sign pull-right"></i></a>
                    <a href='@Url.Action("Create", "Wallet")' class="list-group-item">Add new wallet<i class="glyphicon glyphicon-plus-sign pull-right"></i></a>
                    <a href="@Url.Action("Create", "Category")" class="list-group-item">Add new category<i class="glyphicon glyphicon-plus-sign pull-right"></i></a>
                    <a href='@Url.Action("ShowAllWallets", "Wallet")' class="list-group-item">Wallets<i class="glyphicon glyphicon-folder-close pull-right"></i></a>
                    <a href='@Url.Action("ShowLog", "Log",new {page=1})' class="list-group-item">Log<i class="glyphicon glyphicon-folder-close pull-right"></i></a>
                      
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 bodyPadding">
                    @RenderBody()
                    <hr />
                               
                </div>  

            </div>
        </div>
     
        </div>
 

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>