PersonalMoneyManagerMVC.Web/Controllers/OperationController.cs
using PersonalMoneyManagerMVC.Data.Interface;
using PersonalMoneyManagerMVC.Entity.DTO.Operation;
using PersonalMoneyManagerMVC.Entity.Model;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;
using PersonalMoneyManagerMVC.Entity.Enum;

namespace PersonalMoneyManagerMVC.Web.Controllers
{
    public class OperationController : Controller
    {
        private readonly IRepository<Wallet> _walletRepository;
        private readonly IRepository<Operation> _operationRepository;
        private readonly IRepository<Category> _categoryRepository;
        private readonly IUpdateWalletBalanceService _updateBalanceService;
        private readonly ILogger _logger;
        

        public OperationController(IRepository<Wallet> walletRepo,
                                   IRepository<Operation> operationRepo,
                                   IRepository<Category> categoryRepo,
                                   IUpdateWalletBalanceService service,
                                   ILogger logger)
        {
            _operationRepository = operationRepo;
            _categoryRepository = categoryRepo;
            _walletRepository =  walletRepo;
            _updateBalanceService = service;
            _logger = logger;
        }



        [HttpGet]
        public async Task<ActionResult> Create(Guid id)
        {
            var wallet = _walletRepository.Get().SingleOrDefault(x => x.Id.Equals(id));
            
                if (wallet == null)
                {
                    await _logger.Log(LogType.Error, "Wallet does not exist", null, id.ToString(), "");
                    throw new Exception("Wallet does not exist");
                }


            var listOfCategories = await _categoryRepository.GetList();

            var createOperationDto = new CreateOperationDTO
            {
                Categories = listOfCategories
                    .Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name })
                    .ToList()
            };
            return View(createOperationDto);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateOperationDTO operationDto, Guid id)
        {
            var operationCategoryGuidId = Guid.Parse(operationDto.CategoryId);
         

            var operation = new Operation
            {
                Name = operationDto.Name,
                Comment = operationDto.Comment,
                Summ = operationDto.Summ,
                WalletId = id,
                PayPlace = operationDto.PayPlace,
                CategoryId = operationCategoryGuidId
            };


             _operationRepository.Add(operation);

            await _operationRepository.Save();

            await _logger.Log(LogType.Info, "Operation add", operation,operation.Name,"");
            await _updateBalanceService.UpdateBalance();
            

            return RedirectToAction("Details", "Wallet", new { id,page=1 });
        }

        

    }
}

PersonalMoneyManagerMVC.Web/Controllers/WalletController.cs
using PersonalMoneyManagerMVC.Data.Interface;
using PersonalMoneyManagerMVC.Entity.DTO.Account;
using PersonalMoneyManagerMVC.Entity.Enum;
using PersonalMoneyManagerMVC.Entity.Helper;
using PersonalMoneyManagerMVC.Entity.Model;
using PersonalMoneyManagerMVC.Entity.ViewModel.Operation;
using PersonalMoneyManagerMVC.Entity.ViewModel.Wallet;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;


namespace PersonalMoneyManagerMVC.Web.Controllers
{
    public class WalletController : Controller
    {
        private readonly IRepository<Wallet> _walletRepository;
        private readonly ILogger _logger;
        private readonly IUpdateWalletBalanceService _updateBalanceService;
      
        public  WalletController(IRepository<Wallet> walletRepo,IUpdateWalletBalanceService service, ILogger logger)
        {
            this._walletRepository = walletRepo;
            _updateBalanceService = service;
            _logger = logger;

        }

        
        //Create action

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateWalletDTO walletDto)
        {
            Wallet wallet = new Wallet
            {
                Name = walletDto.Name,
                Currency = walletDto.Currency,
                Type = walletDto.Type
            };


         

            _walletRepository.Add(wallet);
            await _walletRepository.Save();
            await _logger.Log(LogType.Info, "Created account", wallet,wallet.Name,"");
           
            return RedirectToAction("Details",new {id=wallet.Id,page=1});
        }


        //Display all wallets 
        [HttpGet]
        public async  Task<ActionResult> ShowAllWallets()
        {
            await _updateBalanceService.UpdateBalance();
            var wallets = await _walletRepository.Get().Select(x =>  new WalletDetailsViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Balance = x.Balance,
                Created = x.Created.ToString(),
                Currency = x.Currency.ToString(),
                Type = x.Type.ToString()
                

            }).ToListAsync();

            wallets.ForEach(x=>x.SelectIcon());
            return View(wallets);
        }



        //Edit wallet 
        [HttpGet]
        public async Task<ActionResult> Edit(Guid id)
        {
            
                var wallet = _walletRepository
                    .Get()
                    .SingleOrDefault(x => x.Id == id);

            try
            {

          
            if (wallet == null)
            {
                
                await _logger.Log(LogType.Error, "Wallet not exists", null, id.ToString(), "");
                throw new ArgumentException("wtf?");
                }
            }
            catch (Exception e)

            {
                return RedirectToAction("ShowAllWallets","Wallet");

            }
            var walletDto = new CreateWalletDTO
            {
                Currency = wallet.Currency,
                Name = wallet.Name,
                Type = wallet.Type
            };


            return View(walletDto);
        }



        [HttpPost]
        public async Task<ActionResult> Edit(CreateWalletDTO walletDto, Guid id)
        {
            var walletCheck = _walletRepository.Get()
                                        .SingleOrDefault(x => x.Id.Equals(id));

            if (walletCheck == null)
            {
               await _logger.Log(LogType.Error, "Wallet not exists", null, id.ToString(), "");
               
            }
            Wallet wallet = new Wallet
            {
                Id = id,
                Name = walletDto.Name,
                Currency = walletDto.Currency,
                Type = walletDto.Type
            };

            
            await _walletRepository.Update(wallet);
            await _walletRepository.Save();
            await _logger.Log(LogType.Info, "Edited account", wallet,walletCheck.Name,wallet.Name);

           
            return RedirectToAction("Details","Wallet",new {id=wallet.Id,page=1});
        }


        //Wallet details
        [HttpGet]
        public async Task<ActionResult> Details(Guid id,int page)
        {
          
            var wallet =   _walletRepository
                .Get()
                .Include(x => x.OperationsHistory)
                .Include(x => x.OperationsHistory.Select(y => y.Category))
                .SingleOrDefault(x => x.Id == id);

            if (wallet == null)
            {
                
                await _logger.Log(LogType.Error, "Wallet does not exists", null, id.ToString(), "");
                throw new Exception("Wallet does not exist");
            }

            var walletViewModel = new WalletDetailsViewModel
            {
                Id = wallet.Id,
                Name = wallet.Name,
                Created = wallet.Created.ToShortDateString(),
                Currency = wallet.Currency.ToString(),
                Type = wallet.Type.ToString(),
                Balance = wallet.Balance,
                PageInfo = new PageInfo
                {
                    Page =page,
                    PageCount =(int)Math.Ceiling((double)wallet.OperationsHistory.Count/5)
                },
                OperationHistory = wallet.OperationsHistory
                    .OrderByDescending(x=>x.Created)
                    .Skip((page-1)*5)
                    .Select(x => new OperationDetailsViewModel
                    {
                        Id = x.Id,
                        Name = x.Name,
                        Comment = x.Comment,
                        PayPlace = x.PayPlace,
                        Summ = x.Summ,
                        Created = x.Created.ToShortDateString(),
                        Icon = x.Category.Icon,
                        IconColor = x.Category.IconColor
                    })
                    .Take(5)
                    .ToList()
                
            };
            
            walletViewModel.SelectIcon();

            return View(walletViewModel);
        }

        
}

}

PersonalMoneyManagerMVC.Web/Views/Wallet/Create.cshtml
@model PersonalMoneyManagerMVC.Entity.DTO.Account.CreateWalletDTO

@{
    ViewBag.Title = "Create";
}

<div class="container-fluid">
    <div class="row">
        <div class=" col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3>Create wallet:</h3>
                </div>
                <div class="panel-body">
                    <div class="col-lg-offset-4 col-lg-4   col-md-4 col-sm-offset-4 col-md-offset-4 col-sm-4">

                        @using (Html.BeginForm("Create", "Wallet", FormMethod.Post))
                        {

                            @Html.AntiForgeryToken()


                            <div class="form-horizontal  center-block">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">

                                    @Html.LabelFor(model => model.Type, "Name:")
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Type, "Currency:")
                                    @Html.EnumDropDownListFor(model => model.Currency, new { @class = "form-control" })

                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Type, "Type:")
                                    @Html.EnumDropDownListFor(model => model.Type, new { @class = "form-control " })

                                </div>

                            </div>
                                    <div class="form-group">
                                        <div class="col-lg-6 col-md-6 col-sm-6  ">
                                            <input type="submit" value="Create" class="btn btn-success" />
                                        </div>

                                        <div class="col-lg-6 col-md-6 col-sm-6">
                                            <input type="submit" value="Cancel" class="btn btn-danger " />
                                        </div>

                                    </div>
                                
                            
                        }


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PersonalMoneyManagerMVC.Web/Views/Wallet/Details.cshtml
@model PersonalMoneyManagerMVC.Entity.ViewModel.Wallet.WalletDetailsViewModel


@{
    ViewBag.Title = "Details";
}
<div class="container-fluid ">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading" ">
                    <h2 style="width: 30%; padding-bottom: 100pxl;">Wallet: @Html.DisplayFor(model => model.Name)</h2>
                    <h2 style="width: 30%;" >Balance: @Html.DisplayFor(model => model.Balance)</h2>
                        
                    
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Created)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Created)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Currency)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Currency)
                        </dd>
                       

                        <dd>
                            @Html.DisplayFor(model => model.Balance)
                        </dd>

                    </dl>
                </div>
            </div>
            <center>
                <p style="">
                    <button class=" btn btn-info glyphicon glyphicon-plus" onclick="location.href='@Url.Action("Create", "Operation", new { id = Model.Id }, null)'"> Add operation</button>
                    <button class=" btn btn-success glyphicon glyphicon-edit " onclick="location.href=' @Url.Action("Edit", new { id = Model.Id })'"> Edit wallet</button>

                </p>
            </center>
            <!--Operations-->

            <div class="panel panel-default">
                <div class="panel-heading"><h4>Operations:</h4></div>
                <table class="table">
                    <tr>
                        <th>
                           
                        </th>
                        <th>
                            Operation name:
                        </th>
                        <th>
                            Date:
                        </th>
                        <th>
                            Summ:
                        </th>
                        <th>
                            Pay place:
                        </th>
                        <th>
                            Commentary:
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.OperationHistory.OrderByDescending(x=>x.Created))
                    {
                        <tr>
                            <td style="text-align:center;">
                                <i class="@Html.DisplayFor(modelItem => item.Icon) myicons "   style="color:@Html.DisplayFor(modelItem => item.IconColor) "></i>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                        
                            <td>
                                @Html.DisplayFor(modelItem => item.Created)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Summ)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PayPlace)
                            </td>
                            <td style="width: 30%;">
                                @Html.DisplayFor(modelItem => item.Comment)
                            </td>
                            <td>
                                <button type="button" class="btn btn-success glyphicon glyphicon-edit"> @Html.ActionLink(" ", "Edit", new { id = item.Id })</button>

                                <button type="button" class="btn btn-info glyphicon glyphicon-info-sign"> @Html.ActionLink(" ", "Details", new { id = item.Id })</button>

                                <button type="button" class="btn btn-danger glyphicon glyphicon-trash"> @Html.ActionLink(" ", "Delete", new { id = item.Id })</button>
                            </td>
                        </tr>
                    }
                   
                </table>
              
            </div>
            <div class="text-center">
                <ul class="pagination">
               
                
                    @for(int i = 1;i<Model.PageInfo.PageCount+1;i++){

                        <li class="page-item"><a class="page-link" href='@Url.Action("Details","Wallet",new { id = Model.Id,page= i })'>@i</a></li>
                    }

              
                </ul>
            </div>
        </div>
    </div>
</div>

PersonalMoneyManagerMVC.Web/Views/Wallet/Edit.cshtml
@model PersonalMoneyManagerMVC.Entity.DTO.Account.CreateWalletDTO

@{
    ViewBag.Title = "Edit";
}



    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="panel panel-info">
                    <div class="panel-heading" style="background: #4db8ff;color: aliceblue">
                        <h3>Edit wallet:</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-lg-4 col-lg-offset-4">

                            @using (Html.BeginForm("Edit", "Wallet", FormMethod.Post))
                            {

                                @Html.AntiForgeryToken()


                                <div class="form-horizontal  center-block">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">

                                        @Html.LabelFor(model => model.Name, "Name:")
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Currency, "Currency:")
                                        @Html.EnumDropDownListFor(model => model.Currency, new { @class = "form-control" })

                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Type, "Type:")
                                        @Html.EnumDropDownListFor(model => model.Type, new { @class = "form-control " })

                                    </div>

                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <div class="col-lg-6 pull-left">
                                                <input type="submit" value="Create" class="btn btn-success" />
                                            </div>

                                            <div class="col-lg-6 ">
                                                <input type="submit" value="Cancel" class="btn btn-danger pull-right" />
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            }


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

PersonalMoneyManagerMVC.Web/Views/Wallet/ShowAllWallets.cshtml
@model IEnumerable<PersonalMoneyManagerMVC.Entity.ViewModel.Wallet.WalletDetailsViewModel>

@{
    ViewBag.Title = "AllWallets";
}
<div class="container-fluid">
    <div class="col-lg-12">
        <div class="panel panel-info">

            <div class="panel-heading "><h3>All wallets:</h3></div>
            <table class="table table-hover ">


                <tr class="well" style="background: #FFFAFA ;color: black">
                    <th >
                       
                    </th>

                    <th>
                        Wallet name
                    </th>
                    <th>
                        Balance
                    </th>
                    <th>
                        Currency
                    </th>
                    <th>
                        Type
                    </th>
                    <th>
                        Created
                    </th>
                    <th></th>


                </tr>

                @foreach (var item in Model)
                {
                <tr>
                    <td style="text-align:center;">
                        <i class="@Html.DisplayFor(modelItem => item.Icon) myicons" style="color:@Html.DisplayFor(modelItem => item.IconColor)"></i>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Balance)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Currency)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                    <td>
                        <div class="pull-right">
                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn btn-success glyphicon glyphicon-edit" })

                            @Html.ActionLink(" ", "Details", new { id = item.Id,page=1 }, new { @class = "btn btn-info glyphicon glyphicon-info-sign" })

                            <button type="button" class="btn btn-danger glyphicon glyphicon-trash"> @Html.ActionLink(" ", "Delete", new { id = item.Id })</button>
                        </div>

                    </td>
                </tr>
                }

            </table>
        </div>
    </div>
</div>